import { cn } from "@/lib/cn";

/**
 * The supplied Seiran Partners lockup: the arch mark, then "Seiran" in the
 * serif over a gold rule with PARTNERS letterspaced beneath.
 *
 * This replaces a typographic reconstruction. The site used to SET the wordmark
 * from Source Serif 4 and Inter, which meant the logo changed shape whenever a
 * type token moved and never matched the real artwork — PARTNERS was gold and
 * inline, where the real mark puts it under a rule, and green on light grounds.
 *
 * TWO FILES, SWAPPED BY GROUND. The primary lockup is navy, gold and green and
 * is legible only on a light ground; the reversed one is white and gold on
 * navy. Rather than ask each caller which ground it is on — a prop that WILL be
 * forgotten the first time someone drops a lockup into a navy band — both are
 * rendered and CSS shows exactly one, keyed off the same `.on-navy` class every
 * other component already reads. `display: none` keeps the hidden copy out of
 * the accessibility tree, so the name is announced once, not twice.
 *
 * This costs nothing extra: the header sits on white and the footer on navy, so
 * a visitor needs both variants on every page regardless.
 *
 * Sized by HEIGHT, width following, because it lives in a fixed-height bar.
 * Generated by scripts/brand.py — see that file for why the reversed artwork
 * keeps its navy ground and why neither file is trimmed.
 */

/** 2000 x 672, both variants. Must match the canvas scripts/brand.py reports. */
const RATIO = "2000 / 672";

/** Widest the lockup is ever painted, so the browser can pick the right file
 *  before layout. Header and footer both sit well under 320px. */
const SIZES = "220px";

export function Wordmark({ className }: { className?: string }) {
  const img = "h-full w-auto";
  return (
    <span className={cn("block h-11", className)} style={{ aspectRatio: RATIO }}>
      <img
        src="/brand/lockup-640.png"
        srcSet="/brand/lockup-320.png 320w, /brand/lockup-640.png 640w"
        sizes={SIZES}
        width={2000}
        height={672}
        alt="Seiran Partners"
        className={cn(img, "in-[.on-navy]:hidden")}
      />
      <img
        src="/brand/lockup-reversed-640.png"
        srcSet="/brand/lockup-reversed-320.png 320w, /brand/lockup-reversed-640.png 640w"
        sizes={SIZES}
        width={2000}
        height={672}
        alt="Seiran Partners"
        className={cn(img, "hidden in-[.on-navy]:block")}
      />
    </span>
  );
}
